apiVersion: v1
kind: Service
metadata:
  name: travel-agent-backend
spec:
  selector:
    app: travel-agent-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
