apiVersion: v1
kind: Service
metadata:
  name: travel-agent-frontend
spec:
  selector:
    app: travel-agent-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
